---
title: "Pràctica 2"
author: "Pol Moya Betriu\nXavier Martin Bravo"
date: '`r format(Sys.Date(),"%e de %B, %Y")`'
output:
  pdf_document:
    toc: yes
    number_sections: true
  html_document:
    toc: yes
    number_sections: true
toc-title: "Índex"
bibliography: scholar.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries, include=FALSE}
library(knitr)
```

\newpage
# Lectura del fitxer i preparació de les dades

**Llegiu el fitxer `fifa.csv` i guardeu les dades en un objecte amb identificador denominat fifa. A continuació, verifiqueu el tipus de cada variable. Quines variables són de tipus numèric? Quines variables són de tipus categòric?**

```{r message= FALSE, warning=FALSE}
heart_data<-read.csv("./heart_failure_clinical_records_dataset.csv", header=T, sep=",")
#Comprovem que s'ha llegit correctament
head(heart_data)
#Comprovem que el nombre de files és el correcte i que s'han llegit totes les dades
nrow(heart_data)
```






\newpage
# Referències













